### ISSUE TITLE
需要升级到v0.7.0

### ISSUE THREAD

**Issue by chenshenhai** [chenshenhai/deno_note#10]
原有demo和教程是基于`Deno@v0.3.4`
- 在v0.4.0 以后，官方支持了子命令，执行方式变了，原有demo全部跑不动了 o(╯□╰)o
- Deno原生指令使用方式做了重构，需要重新梳理笔记教程

在没完成升级v0.7.0之前，不建议直接git clone 学习。
如果想跑起所有demo案例，必须保证在`Deno@v0.3.4`的环境里

**Comment by awkj** [comment]
alias deno run to deno

**Comment by chenshenhai** [comment]
> alias deno run to deno
oh, thx!
but i tend to keep up with the offical usage and the lastest version. 😁

**Comment by chenshenhai** [comment]
已升级 v0.7.0
