### ISSUE TITLE
deno example.ts 报错

### ISSUE THREAD

**Issue by ravencrown** [chenshenhai/deno_note#13]
➜  Deno $ deno example.ts

 ️⚠️  Deno requests network access to "127.0.0.1:3001". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)] a
listening on 127.0.0.1:3001
thread 'tokio-runtime-worker-0' panicked at 'bad rid', ../../cli/resources.rs:273:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'internal error: entered unreachable code', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:296:26
thread 'main' panicked at 'unexpected state while aborting task: Complete', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.15/src/task/mod.rs:216:21
stack backtrace:
   0:        0x1075ad062 - std::panicking::take_hook::hb25650a43c7b4abc
   1:        0x1075acd2b - std::panicking::take_hook::hb25650a43c7b4abc
   2:        0x1075ad850 - std::panicking::rust_panic_with_hook::h7d6a669f1a899680
   3:        0x1075ad37d - std::panicking::begin_panic_fmt::h5340abefa09e06ca
   4:        0x1075ad2d1 - std::panicking::begin_panic_fmt::h5340abefa09e06ca
   5:        0x1085265d9 - tokio_threadpool::pool::backup_stack::<impl core::convert::From<tokio_threadpool::pool::backup_stack::State> for usize>::from::h22f244c8801cbba7
   6:        0x10852e7af - <tokio_threadpool::shutdown::ShutdownTrigger as core::ops::drop::Drop>::drop::h134c463c5ff9ac9e
   7:        0x10852aafc - <tokio_threadpool::task::Run as core::fmt::Debug>::fmt::h6b791071bd8e3ab7
   8:        0x108521a9a - tokio_threadpool::thread_pool::ThreadPool::shutdown_now::h6c753972452ea1f4
   9:        0x1084fed0d - tokio::runtime::current_thread::runtime::Runtime::run::h9d7c951fd5cdd0a1
  10:        0x1085026a8 - <tokio::runtime::threadpool::Runtime as core::ops::drop::Drop>::drop::h0fc176c521b72182
  11:        0x1087cb1bc - <arc_swap::Protection as core::convert::From<core::option::Option<&arc_swap::debt::Debt>>>::from::h427ca8060d312f50
  12:        0x1088c2368 - <arc_swap::Protection as core::convert::From<core::option::Option<&arc_swap::debt::Debt>>>::from::h427ca8060d312f50
  13:        0x1087b7e46 - <arc_swap::Protection as core::convert::From<core::option::Option<&arc_swap::debt::Debt>>>::from::h427ca8060d312f50
  14:        0x1075ad1e8 - std::panicking::update_panic_count::hb4c719f9cf8762c5
  15:        0x1075bcc4f - __rust_maybe_catch_panic
  16:        0x1075adcce - std::rt::lang_start_internal::hc1ac2c20e9f8edf2
  17:        0x1088c3939 - main
thread panicked while panicking. aborting.
[1]    28483 illegal hardware instruction  deno example.ts

**Comment by chenshenhai** [comment]
@ravencrown 请问您这个是在 deno那个版本？同时是那个例子里的example.ts

**Comment by ravencrown** [comment]
@chenshenhai  
例子是 2.2 https://github.com/chenshenhai/deno_note/blob/master/note/chapter_02/02.md，
环境是 
deno: 0.17.0
v8: 7.7.200
typescript: 3.5.1

**Comment by chenshenhai** [comment]
@ravencrown 目前笔记里的例子是基于 `deno@v0.13.0` 后续我升级和修改一下。如果想跑起笔记里的例子，麻烦在 `deno@v0.13.0`  环境下跑就好了哈

**Comment by ravencrown** [comment]
好的，谢谢大佬

**Comment by chenshenhai** [comment]
@ravencrown 您好，我找到原因了，是文档里写错一句代码，要`await` 等待 TCP对话写完后才能关闭，已经修改好了哈。

```js
await conn.write(encoder.encode(res));
conn.close();
```
