### ISSUE TITLE
2.2 快速使用, 最后执行 在 window10 报错

### ISSUE THREAD

**Issue by mannymu** [chenshenhai/deno_note#14]
![image](https://user-images.githubusercontent.com/15630104/69707570-fbe0b280-1134-11ea-9f7d-6d2af2abed65.png)

需要加上参数--allow-net
以命令：
`deno  --allow-net  .\example.ts`
来启动

**Comment by chenshenhai** [comment]
@mannymu 谢谢指正，已经改正好了哈
