### ISSUE TITLE
例子需要修复成TS的Strict Mode

### ISSUE THREAD

**Issue by chenshenhai** [chenshenhai/deno_note#16]
Deno@0.34.0 把TS模式设置默认 严格模式，本书的例子都要修改一遍，以支持接下来的最新版本的Deno

```sh
Enable TS strict mode by default 
```

**Comment by awkj** [comment]
感觉 deno 应该不仅仅是默认严格模式，就应该 only 严格模式，禁用掉一些诸如 var 等特性才比较好，js 包袱太多了

**Comment by chenshenhai** [comment]
> 感觉 deno 应该不仅仅是默认严格模式，就应该 only 严格模式，禁用掉一些诸如 var 等特性才比较好，js 包袱太多了

Deno官方定位是 `A secure JavaScript and TypeScript runtime`，就意味着可以直接运行 `JavaScript` 源码，所以暂时应该不会强行only  strict mode

**Comment by chenshenhai** [comment]
全部例子和笔记文档都更新到支持 `Deno@0.34.0` 的 TS `Strict Mode`
