### ISSUE TITLE
目录操作方法返回的结果似乎不是FileInfo[]类型

### ISSUE THREAD

**Issue by asins** [chenshenhai/deno_note#20]
```js
const files: Deno.FileInfo[] = Deno.readDirSync("./assets");
```

指定`files`为`Deno.FileInfo[]`类型后会发现单个file中的属性都无法访问，很奇怪的的事。

当前使用的版本是`0.4.1`

**Comment by chenshenhai** [comment]
@asins 您好，这个问题是因为 最新版 Deno 已经更新了 API的结果，会返回一个迭代器类型的数据 `Iterable<DirEntry>` 其中 `DirEntry` 包含了判断是否为目录`isDirectory`，是否为文件`isFile`的属性

你可以换成以下方式试试看

```js
const rs = Deno.readDirSync("./assets");
for (const dirEntry of Deno.readDirSync("./assets")) {
  console.log(dirEntry.name);
}
```

可参考官方API文档 [https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.DirEntry](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.DirEntry)
