### ISSUE TITLE
考虑使用 pagic 来搭建网站吗？

### ISSUE THREAD

**Issue by xcatliu** [chenshenhai/deno_note#24]
要不要使用 [Pagic](https://github.com/xcatliu/pagic) 搭建一个网站？若 @chenshenhai 同意的话，我可以帮忙完成第一版的工作😊

Pagic 是用 Deno 实现的一个静态网站生成器，这是第一个使用 Pagic 搭建的网站：
https://ts.xcatliu.com/

特性：
- github actions 持续集成发布
- 静态网页 + 单页应用——页面初次加载性能最优，页面间跳转时能无缝跳转
- 深色模式
- gitalk 评论
- 更多功能开发中

这是第二个使用 Pagic 搭建的网站：
https://deno-tutorial.js.org/

**Comment by chenshenhai** [comment]
@xcatliu 感谢大佬邀请，我周末找个时间体验看看 😁

**Comment by xcatliu** [comment]
@chenshenhai deno-tutorial 已上线： https://deno-tutorial.js.org/
