### ISSUE TITLE
逐步替换 import  "deno"成全局Deno变量

### ISSUE THREAD

**Issue by chenshenhai** [chenshenhai/deno_note#3]
Deno@v0.3.0 已经支持全局变量`Deno`，Deno官方声明了未来的版本将不会兼容 ` import deno from  "deno"` 的方式，后续笔记例子源码需要全面替换修改。

> 官方v0.3.0 说明
> The major API change in this release is that instead of importing a "deno" module, there is now a global variable called Deno. This allows code that does deno-specific stuff to still operate in browsers. We will remain backward compatible with the old way of importing core functionality, but it will be removed in the near future, so please update your code. 

https://github.com/denoland/deno/blob/master/Releases.md#v030--20190218

**Comment by kevinkassimo** [comment]
当然也可以做类似`const { readFile } = Deno;`之类的简单替换import stmts

**Comment by chenshenhai** [comment]
已经替换完毕
