### ISSUE TITLE
你好 请问window上面 导入模块找不到是什么问题呢？ vscode 导入模块的时候还会报错误。

### ISSUE THREAD

**Issue by SmartTuwei** [chenshenhai/deno_note#4]
![image](https://user-images.githubusercontent.com/29091787/55131675-97f78b80-515a-11e9-8459-3409bf03eaff.png)

**Comment by SmartTuwei** [comment]
![image](https://user-images.githubusercontent.com/29091787/55131715-c4130c80-515a-11e9-9c7a-62329017ef3e.png)

**Comment by chenshenhai** [comment]
- 全局变量 Deno 要在deno@0.3.0 以上的环境才支持，你可以升级一下你本地的deno环境。
- vscode的报错，你可以在插件市场使用一下 deno的插件
